query AllArticles ($tag: String, $category: String) {
  posts(where: {tag: $tag}) {
    edges {
      node {
        slug
        excerpt
        id
        title
        content
        featuredImage {
          node {
            sourceUrl
            srcSet
            altText
          }
        }
        categories (where: {nameLike: $category}) {
          edges {
            node {
              name
              id
            }
          }
        }
        tags {
          edges {
            node {
              name
            }
          }
        }
      }
    }
  }
}
