query MyQuery($category: ID!, $first: Int!, $after: String) {
  category(id: $category, idType: NAME) {
    posts(first: $first, after: $after) {
        nodes {
          slug
          id
          title
          featuredImage {
            node {
              sourceUrl
              altText
            }
          }
        }
      pageInfo {
        total
        endCursor
        hasNextPage
      }
    }
    name
    id
  }
}
