query Article($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    title
    content
    slug
    excerpt
    categories {
      nodes {
        name
        id
      }
    }
    author {
      node {
        firstName
        lastName
        id
        avatar {
          url
        }
      }
    }
    date
    featuredImage {
      node {
        sourceUrl
      }
    }
    seo {
      metaDesc
      title
    }
  }
}
