query ArticleListQuery($first: Int!, $after: String) {
  posts (first: $first, after: $after) {
    edges {
      cursor
      node {
        title
        slug
      }
    }
    pageInfo {
      total
      endCursor
      hasNextPage
    }
  }
}
