query Article ($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    title
    content
    slug
    author {
      node {
        firstName
        lastName
        id
        avatar {
          url
        }
      }
    }
    date
    featuredImage {
      node {
        sourceUrl
      }
    }
  }
}