query ArticleListQuery($first: Int!, $after: String) {
  posts(first: $first, after: $after) {
    edges {
      cursor
      node {
        title
        slug
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        categories {
          edges {
            node {
              name
              id
            }
          }
        }
      }
    }
    pageInfo {
      total
      endCursor
      hasNextPage
    }
  }
}
