query CategoriesQuery ($category: String) {
  posts(where: {categoryName: $category}, first: 6) {
    nodes {
      title
      excerpt
      slug
      id
      categories {
          nodes {
            name
            id
          }
      }
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
}
