query MyQuery($category: String) {
  posts(where: {categoryName: $category}, first: 4) {
    nodes {
      title
      excerpt
      slug
      id
      categories {
        edges {
          node {
            name
            id
          }
        }
      }
      featuredImage {
        node {
          sourceUrl
        }
      }
    }
  }
}
