query MyQuery($name: ID!) {
  category(id: $name, idType: NAME) {
    posts {
      edges {
        node {
          title
          excerpt(format: RENDERED)
          slug
          id
        }
      }
    }
  }
}
