query MyQuery($tag: ID!) {
  tag(id: $tag, idType: NAME) {
    posts (first: 2) {
      nodes {
        id
        slug
        excerpt
        title
        categories {
          nodes {
            id
            name
          }
        }
        featuredImage {
          node {
            sourceUrl
            srcSet
          }
        }
      }
    }
  }
}