query MyQuery ($tag: ID!){
  tag(id: $tag, idType: NAME) {
    posts {
      nodes {
        id
        slug
        excerpt
        title
        categories {
          nodes {
            id
            name
          }
        }
        featuredImage {
          node {
            id
            mediaItemUrl
          }
        }
      }
    }
  }
}

