query SideArticleGridQuery {
  posts(first: 5) {
    nodes {
      title
      slug
      id
      featuredImage {
        node {
          sourceUrl
          altText
        }
      }
      categories {
        nodes {
          name
          id
        }
      }
    }
  }
}