query GetAllPosts ($first: Int, $last: Int, $endCursor: String, $startCursor: String) {
      posts(first:$first last:$last after:$endCursor before:$startCursor) {
        edges {
          node {
            title
            date
            id
            slug
            excerpt
            featuredImage {
              node{
              	sourceUrl 
                srcSet
                altText
                id
              }
            }
          }
          cursor
        }
      pageInfo {
        hasNextPage
        startCursor
        endCursor
        }
      }
    }